# Generated by Django 5.2.7 on 2025-11-04 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, help_text='Solo necesario para delivery')),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro en local'), ('delivery', 'Delivery')], default='retiro', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('mercadopago', 'Mercado Pago')], default='efectivo', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del pedido', max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Aclaraciones o instrucciones especiales')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa del producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en pesos argentinos', max_digits=10)),
                ('imagen', models.ImageField(help_text='Imagen del producto (recomendado: 800x600px)', upload_to='productos/')),
                ('disponible', models.BooleanField(default=True, help_text='¿Está disponible para la venta?')),
                ('destacado', models.BooleanField(default=False, help_text='¿Mostrar en la página principal?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu.categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la compra', max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
            options={
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
    ]
